Hide aggregates by default and change -a to show them [3.0]

diff --git a/viotop b/viotop
--- a/viotop
+++ b/viotop
@@ -4,7 +4,7 @@
 #
 # $Title: Script to generate top-like statistics for VFS I/O under Linux $
 # $Copyright: 2020 Devin Teske. All rights reserved. $
-# $FrauBSD: viotop/viotop 2020-04-19 18:58:18 -0700 freebsdfrau $
+# $FrauBSD: viotop/viotop 2020-04-19 19:49:54 -0700 freebsdfrau $
 #
 ############################################################ DEFAULTS
 
@@ -12,7 +12,7 @@ DEFAULT_INTERVAL=2 # seconds
 
 ############################################################ GLOBALS
 
-VERSION='$Version: 2.5 $'
+VERSION='$Version: 3.0 $'
 
 pgm="${0##*/}" # Program basename
 
@@ -25,7 +25,6 @@ FAILURE=1
 #
 # Command-line options
 #
-AGGREGATE_VIEW=				# -a
 DEBUG=					# -d
 FILTER_GROUP=				# -G group
 FILTER_TYPE=				# -T type
@@ -36,6 +35,7 @@ NO_NAMES=				# -n
 NSAMPLES=				# -N num
 OUTPUT_JSON=				# -j
 RAW_VIEW=				# -r
+SHOW_AGGREGATES=			# -a
 VIEW_COMM=				# -c
 VIEW_GROUP=				# -g
 VIEW_PID=				# -p (default)
@@ -86,7 +86,7 @@ usage()
 
 	printf "Usage: %s [OPTIONS] [--] [comm]\n" "$pgm"
 	printf "Options:\n"
-	printf "$optfmt" "-a" "Only show aggregate subtotals."
+	printf "$optfmt" "-a" "Show aggregate subtotals."
 	printf "$optfmt" "-c" "View read/write activity by command name."
 	printf "$optfmt" "-d" "Debug. Print bpftrace script and exit."
 	printf "$optfmt" "-G group" "Group filter (name or id)."
@@ -264,7 +264,7 @@ bpf_map_ids()
 #
 while getopts acdG:ghi:JjN:nP:prsT:tU:uvw flag; do
 	case "$flag" in
-	a) AGGREGATE_VIEW=1 ;;
+	a) SHOW_AGGREGATES=1 ;;
 	c) VIEW=COMM VIEW_COMM=1 ;;
 	d) DEBUG=1 RAW_VIEW=1 ;;
 	G) FILTER_GROUP="$OPTARG" ;;
@@ -298,12 +298,6 @@ shift $(( $OPTIND - 1 ))
 FILTER_COMM="$1"
 
 #
-# Check if both `-a' and `-T type' were given
-#
-! [ "$AGGREGATE_VIEW" -a "$FILTER_TYPE" ] ||
-	die "-T type cannot be combined with -a"
-
-#
 # Silently ignore previous view options unless JSON output
 #
 [ "$VIEW$OUTPUT_JSON" ] || VIEW=PID VIEW_PID=1
@@ -315,6 +309,14 @@ if [ ! "$OUTPUT_JSON" ]; then
 	TYPE) VIEW_COMM= VIEW_GROUP= VIEW_PID= VIEW_USER= ;;
 	USER) VIEW_COMM= VIEW_GROUP= VIEW_PID= VIEW_TYPE= ;;
 	esac
+fi
+
+#
+# Check if both `-a' and `-t'/`-T type' were given
+#
+if [ "$SHOW_AGGREGATES" -a ! "$OUTPUT_JSON" ]; then
+	[ ! "$VIEW_TYPE" ] || die "-a cannot be combined with -t"
+	[ ! "$FILTER_TYPE" ] || die "-a cannot be combined with -T type"
 fi
 
 #
@@ -1206,15 +1208,14 @@ EOF
 	echo EXIT:$? >&9 # Send status to post-processor
 
 } | awk -v cols=$cols \
-	-v aggregate_view=${AGGREGATE_VIEW:-0} \
 	-v debug=${DEBUG:-0} \
-	-v filter_type=${FILTER_TYPE:+1} \
 	-v interval=$INTERVAL_SECONDS \
 	-v no_names=${NO_NAMES:-0} \
 	-v nsamples=${NSAMPLES:-0} \
 	-v output_json=${OUTPUT_JSON:-0} \
 	-v raw_view=${RAW_VIEW:-0} \
 	-v rows=$rows \
+	-v show_aggregates=${SHOW_AGGREGATES:-0} \
 	-v view="$VIEW" \
 	-v wide_view=${WIDE_VIEW:-0} \
 	'####################################### BEGIN
@@ -1399,7 +1400,7 @@ EOF
 		map_value = $NF
 
 		map_skey = ""
-		if (map_view != "type" && !filter_type) {
+		if (show_aggregates) {
 			map_key = sprintf("%s, %s",
 				map_keys[1], map_keys[2])
 			map_skey = sprintf("*, %s", map_keys[2])
@@ -1590,8 +1591,7 @@ EOF
 		cred_write, write_bar, write_bar_pct, write_rate, pch)
 	{
 		pch = "="
-		if (map_view != "type" && cred !~ /^\*, /) {
-			if (aggregate_view) return
+		if (show_aggregates && cred !~ /^\*, /) {
 			pch = "-"
 		}
 
